# Generated by Django 2.2 on 2020-09-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='desc.')),
                ('short_description', models.CharField(blank=True, max_length=64, verbose_name='short desc.')),
                ('image', models.ImageField(blank=True, upload_to='products_img')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='status')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ProductCategory', verbose_name='category')),
            ],
        ),
    ]
