# Generated by Django 2.2 on 2020-10-02 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64, verbose_name='place')),
                ('phone_number', models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(regex='\\d{3,4}\\s-\\s\\d{3,4}\\s-\\s\\d{3,4}')], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=64, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='address')),
                ('mapcode', models.CharField(blank=True, max_length=512, verbose_name='mapcode')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
